---
- name: Include initial OS-specific tasks
  ansible.builtin.include_tasks: init_{{ ansible_os_family | lower }}.yml
  vars:
    _cvmfs_role: publishers
    _cvmfs_upgrade: "{{ cvmfs_upgrade_server }}"

- name: Include key setup tasks
  ansible.builtin.include_tasks: keys.yml

- name: Change Apache listen port
  ansible.builtin.lineinfile:
    dest: "{{ cvmfs_apache_conf_file }}"
    line: Listen {{ cvmfs_stratum1_apache_port }}
    regexp: ^Listen\s+
    backup: true
  when: cvmfs_config_apache
  notify:
    - Reload apache

- name: Include stratumN tasks
  ansible.builtin.include_tasks: stratumN.yml

- name: Include Apache tasks
  ansible.builtin.include_tasks: apache.yml

- name: Ensure replicas are configured
  ansible.builtin.command: >-
    /usr/bin/cvmfs_server add-replica -o {{ item.owner | default('root') }}
      http://{{ item.stratum0 }}/cvmfs/{{ item.repository }}
      {{ item.key_dir | default('/etc/cvmfs/keys') }}/{{ item.repository }}.pub
  args:
    creates: /etc/cvmfs/repositories.d/{{ item.repository }}
  loop: "{{ cvmfs_repositories }}"
  register: __cvmfs_add_replica_result
  notify:
    - Restart apache

# Ideally we could use item.stratum0_url_scheme directly in `cvmfs_server add-replica` above, but it appears not to
# support it, so we instead have to change it after the fact
- name: Configure replica stratum0 URLs
  ansible.builtin.lineinfile:
    path: /etc/cvmfs/repositories.d/{{ item.repository }}/server.conf
    regexp: ^CVMFS_STRATUM0=https?://[^/]+/(.*)
    line: CVMFS_STRATUM0={{ item.stratum0_url_scheme | default("http") }}://{{ item.stratum0 }}/\1
    backrefs: true
  loop: "{{ cvmfs_repositories }}"

- name: Include repository server options tasks
  ansible.builtin.include_tasks: options.yml
  vars:
    _cvmfs_repo_option_key: server

