---
# handlers file for cvmfs.publisher.gateway

- name: Restart apache
  ansible.builtin.service:
    name: "{{ cvmfs_apache_service_name }}"
    state: restarted

- name: Reload apache
  ansible.builtin.service:
    name: "{{ cvmfs_apache_service_name }}"
    state: reloaded
